# Enable code coverage.
coverage:
  if: true
  paths:
    - .gocover/coverage.out

# Enable Summary
summary:
  if: true
  hideFooterLink: true

# Enable updating pull request body.
body:
  if: is_pull_request
  hideFooterLink: true

# Disable pull request comment (uses body)
comment:
  if: false
  hideFooterLink: true

# Store coverage report as actions artifact if on default branch.
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}

# Diff reference to github artifact.
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}

# Disable processing test execution time.
testExecutionTime:
  if: false

# Disable processing code to test ratio.
codeToTestRatio:
  if: false
