name: dependency-review
on:
  pull_request:
permissions:
  contents: read
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Dependency Review"
        uses: actions/dependency-review-action@v3
        with:
          allow-licenses: BSD-3-Clause, MIT, Apache-2.0, MPL-2.0, Unlicense
