name: labels
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  labels:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Labels
        run: |
          jq -r '.[] | "\(.name) --force --color=\(.color) --description=\"\(.description)\""' .github/labels.json | xargs -L1 gh label create
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
