name: test
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go:
          - stable
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          check-latest: true
          cache: true
          go-version: ${{ matrix.go }}

      - name: Go version
        run: go version

      - name: Run tests
        run: go test -v -cover -covermode=atomic -coverprofile coverage.out  ./...
        env:
          GO_GITHUBAPP_TEST_OWNER: ${{ vars.GO_GITHUBAPP_TEST_OWNER }}
          GO_GITHUBAPP_TEST_APP_ID: ${{ vars.GO_GITHUBAPP_TEST_APP_ID }}
          GO_GITHUBAPP_TEST_APP_PRIVATE_KEY: ${{ secrets.GO_GITHUBAPP_TEST_APP_PRIVATE_KEY }}

      - name: Ensure examples work (workspaces)
        run: |
          go work init .
          go work use .
          go work use ./examples/go-github-readme
          go run github.com/tprasadtp/go-githubapp/examples/app-token@latest -help
          go run github.com/tprasadtp/go-githubapp/examples/go-github-readme@latest -help
